name: BUILD

on:
    pull_request:
        branches: [] # add branches in future for multiple contributers

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Install dependencies (Yarn Workspaces)
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint

            - name: Check types
              run: pnpm check-types

            - name: Format Check (Prettier)
              run: pnpm format --check

            - name: Cache turbo build
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ hashFiles('**/tsconfig.json', '**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Build
              run: pnpm build
              env:
                  NODE_ENV: production
